# Generated by Django 5.1 on 2024-09-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elasticsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('scheme', models.CharField(choices=[('http', 'http'), ('https', 'https')], max_length=255)),
            ],
            options={
                'db_table': 'Elasticsearch',
            },
        ),
    ]
